### ISSUE TITLE
how to set the font size？

### ISSUE THREAD

**Issue by tonglei100** [boopathikumar018/docsify-darklight-theme#3]
the chinese font size is bigger, how to set the font size?
please look here: https://sweeter.io/#/sweetest/

**Comment by boopathikumar018** [comment]
which font size you want to change. body or left navigation ?

**Comment by tonglei100** [comment]
> which font size you want to change. body or left navigation ?

I want to change the body font size. thank you!

And, Should the sun/moon icon move to the menu as the last item? like:

                                                                           HOME | DOCS | [ICON]

**Comment by boopathikumar018** [comment]
[check](https://github.com/tonglei100/tonglei100.github.io/pull/1). 
> And, Should the sun/moon icon move to the menu as the last item? like:
> 
> ```
>                                                                        HOME | DOCS | [ICON]
> ```

It is external plugin for docsify.  Can't move there since every one will not use navigation bar.
