### ISSUE TITLE
Toggle button not working on mobile

### ISSUE THREAD

**Issue by hmble** [boopathikumar018/docsify-darklight-theme#9]
Whenever I click darkmode toggle button, a new tab for git project opens. Maybe the reason for this is that toggle button is not properly aligned with github corner button.

Any way to remove github fork button or align toggle button ?

**Comment by boopathikumar018** [comment]
![IMG_525834C626EE-1](https://user-images.githubusercontent.com/10001746/120125724-877a4a00-c1d7-11eb-8214-1d7255461e41.jpeg)

To avoid the overlap of GitHub corner. Now theme switcher will move to left on mobile screen.
